server:
  port: 3000
#  key-store: classpath:sample.jks
#  key-store-password: secret
#  key-password: password
spring:
  data:
    rest:
      basePath: /api
      returnBodyOnCreate: true
      returnBodyOnUpdate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/accounting