server:
  port: 3000
  context-path: /accounting
#  ssl:
#    key-store: classpath:sample.jks
#    key-store-password: secret
#    key-password: password
spring:
  data:
    rest:
      basePath: /api
      returnBodyOnCreate: true
      returnBodyOnUpdate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

management:
  context-path: /mgmt