source 'https://rubygems.org'

gem 'rails', '4.2.0.beta2'
gem 'rails-api'
gem 'spring', group: :development
gem 'pry-rails', group: :development
gem 'pg'
gem 'grape'
gem 'ffaker'
gem 'rack-cors', require: 'rack/cors'