source 'https://rubygems.org'

gem 'rails', '4.2.0.beta2'
gem 'rails-api'
gem 'pg'
gem 'grape'
gem 'hashie_rails'
gem 'rack-cors', require: 'rack/cors'

group :test, :development do
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'fabrication'
  gem 'json_spec'
  gem 'ffaker'
end