source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'rails-api'
gem 'pg'
gem 'grape', '~> 0.10.1'
gem 'hashie_rails'
gem 'rack-cors', '~> 0.3.1', require: 'rack/cors'

group :test, :development do
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'fabrication'
  gem 'json_spec'
  gem 'ffaker'
end

group :test do
  gem 'simplecov'
  gem 'simplecov-teamcity-summary'
end